@extends('layouts.app')

@section('content')
    <h1>About page</h1>
    <p>
    Stephen Edwin King was born in Portland, Maine, on September 21, 1947. His father, Donald Edwin King, was a merchant seaman[citation needed] who was born with the surname Pollock but changed it to King as an adult.[10][11][12] King's mother was Nellie Ruth King (née Pillsbury).[12] His parents were married in Scarborough, Maine, on July 23, 1939.[13] Shortly afterwards, they lived with Donald's family in Chicago before moving to Croton-on-Hudson, New York.[14] King's parents returned to Maine towards the end of World War II, living in a modest house in Scarborough. When King was two years old, his father left the family. His mother raised him and his older brother David by herself, sometimes under great financial strain. They moved from Scarborough and depended on relatives in Chicago; Croton-on-Hudson; West De Pere, Wisconsin; Fort Wayne, Indiana; Malden, Massachusetts; and Stratford, Connecticut.[15][16] When King was 11, his family moved to Durham, Maine, where his mother cared for her parents until their deaths. She then became a caregiver in a local residential facility for the mentally challenged.[1] King was raised Methodist,[17][18] but lost his belief in organized religion while in high school. While no longer religious, he says he chooses to believe in the existence of God.[19]
    </p><p>
    As a child, King apparently witnessed one of his friends being struck and killed by a train, though he has no memory of the event. His family told him that after leaving home to play with the boy, King returned speechlessly and seemingly in shock. Only later did the family learn of the friend's death. Some commentators have suggested that this event may have psychologically inspired some of King's darker works,[20] but King makes no mention of it in his memoir On Writing (2000). He related in detail his primary inspiration for writing horror fiction in his non-fiction Danse Macabre (1981), in a chapter titled "An Annoying Autobiographical Pause". He compared his uncle's dowsing for water using the bough of an apple branch with the sudden realization of what he wanted to do for a living. That inspiration occurred while browsing through an attic with his elder brother, when King uncovered a paperback version of an H. P. Lovecraft collection of short stories he remembers as The Lurker in the Shadows, that had belonged to his father. King told Barnes & Noble Studios during a 2009 interview, "I knew that I'd found home when I read that book."[21]
    </p><p>
    King attended Durham Elementary School and graduated from Lisbon Falls High School in Lisbon Falls, Maine, in 1966.[22] He displayed an early interest in horror as an avid reader of EC horror comics, including Tales from the Crypt, and he later paid tribute to the comics in his screenplay for Creepshow. He began writing for fun while still in school, contributing articles to Dave's Rag, the newspaper his brother published with a mimeograph machine, and later began selling stories to his friends based on movies he had seen (he was forced to return the profits when discovered by teachers.) The first of his stories to be independently published was "I Was a Teenage Grave Robber", which was serialized over four issues (three published and one unpublished) of a fanzine, Comics Review, in 1965. That story was published the following year in a revised form as "In a Half-World of Terror" in another fanzine, Stories of Suspense, edited by Marv Wolfman.[23] As a teen, King also won a Scholastic Art and Writing Award.[24]
    </p><p>
    From 1966, King studied at the University of Maine, graduating in 1970 with a Bachelor of Arts in English.[25] That year, his daughter Naomi Rachel was born. He wrote a column, Steve King's Garbage Truck, for the student newspaper, The Maine Campus, and participated in a writing workshop organized by Burton Hatlen.[26] King held a variety of jobs to pay for his studies, including janitor, gas pump attendant, and worker at an industrial laundry. King met his wife, fellow student Tabitha Spruce, at the university's Fogler Library after one of Professor Hatlen's workshops; they wed in 1971.[26] 
    </p>
@endsection